---
foreman:
  Farm-A: #Farm name decalred with -f
    protocol: "https"
    hostname: "1.1.1.1"
    hostport: "8080"
    username: ""
    password: "" #Leave Blank to be prompted!

  Farm-B:
    protocol: "https"
    hostname: "1.1.1.2"
    hostport: "8080"
    username: ""
    password: ""
